name: animated_login
description: Animated Login for Flutter. You can welcome your users with this beautiful animated screen that gives functionality for both login and sign up.
<<<<<<< HEAD
version: 1.3.0
=======
version: 1.5.1
>>>>>>> 15afffa4778b068a51a25368018e9755cabf80f5
homepage: https://github.com/bahricanyesil/flutter-animated-login
repository: https://github.com/bahricanyesil/flutter-animated-login

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.2
  animations: ^2.0.2
  async: ^2.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4

flutter:
